name: Build Android App with CMake and Submodules

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.6

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}

    - name: Install Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O commandlinetools.zip
        unzip -q commandlinetools.zip -d android-sdk
        echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        echo "$PWD/android-sdk/tools/bin" >> $GITHUB_PATH
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Install Android NDK
      run: |
        wget -q https://googledownloads.cn/android/repository/android-ndk-r27-linux.zip -O ndk-bundle.zip
        unzip -q ndk-bundle.zip
        echo "ANDROID_NDK_HOME=$PWD/ndk-bundle" >> $GITHUB_ENV
        echo "$PWD/ndk-bundle" >> $GITHUB_PATH

    - name: Set CC environment variable for aarch64
      run: echo "CC=aarch64-linux-android-clang" >> $GITHUB_ENV

    - name: Set CC environment variable for armhf
      run: echo "CC=arm-linux-androideabi-clang" >> $GITHUB_ENV

    - name: Install CMake
      run: sudo apt-get install cmake -y

    - name: Configure CMake for audio_plugin (arm64)
      working-directory: audio_plugin
      run: cmake .. -DCMAKE_TOOLCHAIN_FILE=../cross-arm64.cmake -DCMAKE_C_COMPILER=$CC

    - name: Build audio_plugin (arm64)
      working-directory: audio_plugin
      run: cmake --build build64 -- -j8

    - name: Configure CMake for android_sysvshm (armhf)
      working-directory: winlator/android_sysvshm
      run: cmake .. -DCMAKE_TOOLCHAIN_FILE=../cross-armhf.cmake -DCMAKE_C_COMPILER=$CC

    - name: Build android_sysvshm (armhf)
      working-directory: winlator/android_sysvshm
      run: cmake --build build -- -j8

    - name: Assemble and Test with Gradle
      run: ./gradlew assembleDebug test

    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: build/reports

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: app/build/outputs/apk/debug/
